<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sde-package-builder</AssemblyName>
    <RootNamespace>Sde.PackageBuilder</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Sde.Core/Sde.Core.fsproj" />
  </ItemGroup>

</Project>
